# Generated by Django 4.2.7 on 2024-09-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_user_name_newuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='username',
        ),
        migrations.AddField(
            model_name='newuser',
            name='user_name',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='user_name'),
            preserve_default=False,
        ),
    ]
