# Generated by Django 4.2.7 on 2024-09-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_newuser_username_newuser_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='user_name',
        ),
        migrations.AddField(
            model_name='newuser',
            name='username',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
    ]
