# Generated by Django 5.1.1 on 2024-09-10 00:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_newuser_user_name_newuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='phone',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must be exactly 10 digits')], verbose_name='phone number'),
        ),
    ]
