# Generated by Django 5.1.1 on 2024-09-29 23:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(verbose_name='bag weight')),
                ('number', models.IntegerField(verbose_name='bags number')),
            ],
        ),
        migrations.CreateModel(
            name='Containers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='containers number')),
                ('capacity', models.IntegerField(verbose_name='container Capacity')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50, verbose_name='state')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60, verbose_name='first name')),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
                ('phone', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must be exactly 10 digits')], verbose_name='phone number')),
                ('zone', models.CharField(max_length=30, verbose_name='state')),
                ('olive_type', models.CharField(choices=[('green', 'Green'), ('red', 'Red'), ('black', 'Black')], default='green', max_length=5)),
                ('Containers', models.ManyToManyField(related_name='customer_containers', to='customer.containers', verbose_name='bags')),
                ('bags', models.ManyToManyField(related_name='customer_bags', to='customer.bags', verbose_name='bags')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_from_state', to='customer.state', verbose_name='state')),
            ],
        ),
    ]
