# Generated by Django 5.1.1 on 2024-09-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.CharField(max_length=50, unique=True, verbose_name='state'),
        ),
    ]
