# Generated by Django 5.1.1 on 2024-09-29 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_state_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['state']},
        ),
    ]
