# Generated by Django 5.1.1 on 2024-09-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_state_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State',
            new_name='States',
        ),
        migrations.AlterField(
            model_name='customer',
            name='Containers',
            field=models.ManyToManyField(related_name='customer_containers', to='customer.containers', verbose_name='Containers'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zone',
            field=models.CharField(max_length=30, verbose_name='Zone'),
        ),
    ]
