# Generated by Django 5.1.1 on 2024-09-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_olive_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
    ]
