# Generated by Django 5.1.1 on 2024-09-30 17:17

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_states_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='states',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Containers',
            new_name='containers',
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_joined',
            field=models.DateField(default=customer.models.current_date),
        ),
    ]
