# Generated by Django 5.1.1 on 2024-09-30 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_states_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bags',
            new_name='Bag',
        ),
        migrations.RenameModel(
            old_name='Containers',
            new_name='Container',
        ),
    ]
