# Generated by Django 4.2.7 on 2024-09-30 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_rename_bags_bag_rename_containers_container'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='bags',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='containers',
        ),
        migrations.AddField(
            model_name='bag',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bags', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='container',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='customer.customer'),
        ),
    ]
