# Generated by Django 5.1.1 on 2024-10-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_remove_customer_bags_remove_customer_containers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='days_gone',
            field=models.IntegerField(default=0, verbose_name='days gone by'),
        ),
    ]
