# Generated by Django 5.1.1 on 2024-10-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_customer_days_gone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_printed',
            field=models.BooleanField(default=False, verbose_name='is customer printed'),
        ),
    ]
