# Generated by Django 5.1.1 on 2024-10-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_alter_customer_olive_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='olive_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Green'), (2, 'Red'), (3, 'Black')], null=True),
        ),
    ]
