# Generated by Django 5.1.1 on 2024-10-13 22:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_alter_customer_olive_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=100, verbose_name='Reason for cancellation'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is user active'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
