# Generated by Django 5.1.1 on 2024-10-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_customer_cancel_reason_customer_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reason for cancellation'),
        ),
    ]
