# Generated by Django 5.1.1 on 2024-10-23 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_alter_customer_cancel_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=50, unique=True, verbose_name='zone')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_from_state', to='customer.states', verbose_name='state')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_from_zone', to='customer.zones', verbose_name='zone'),
        ),
    ]
