# Generated by Django 5.1.1 on 2024-10-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_zones_alter_customer_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='id2',
            field=models.IntegerField(default=0, editable=False, verbose_name='id2'),
            preserve_default=False,
        ),
    ]
