# Generated by Django 5.1.1 on 2024-10-29 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_bag_id2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='id2',
        ),
    ]
