# Generated by Django 5.1.1 on 2024-11-04 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_customer_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='modification_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='modification date'),
        ),
        migrations.AddField(
            model_name='customer',
            name='modification_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_modified', to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='modified',
            field=models.BooleanField(default=False, verbose_name='is customer modified'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_from_state', to='customer.states', verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_from_zone', to='customer.zones', verbose_name='zone'),
        ),
    ]
