# Generated by Django 5.1.1 on 2024-11-04 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_customer_modification_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cancel_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='modification date'),
        ),
        migrations.AddField(
            model_name='customer',
            name='cancel_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_canceler', to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
    ]
