# Generated by Django 4.2.7 on 2024-09-10 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='company')),
                ('address', models.CharField(max_length=80, verbose_name='address')),
                ('phone1', models.IntegerField(validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must be exactly 10 digits')], verbose_name='phone number 1')),
                ('phone2', models.IntegerField(blank=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must be exactly 10 digits')], verbose_name='phone number 2')),
                ('sign', models.CharField(blank=True, max_length=100, verbose_name='sign')),
                ('price_green_olive', models.IntegerField(default=0, verbose_name='price of green olive')),
                ('price_tayeb_olive', models.IntegerField(default=0, verbose_name='price of tayb olive')),
                ('price_dro_olive', models.IntegerField(default=0, verbose_name='price of drew olive')),
            ],
        ),
    ]
