# Generated by Django 4.2.7 on 2024-09-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='session_start',
            field=models.DateField(blank=True, null=True, verbose_name='session start'),
        ),
    ]
