# Generated by Django 4.2.7 on 2024-09-10 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_session_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='session',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator('^\\d{4}/\\d{4}$', 'Session must be in the format YYYY/YYYY')], verbose_name='session'),
        ),
    ]
